### PR TITLE
PR for Assignment 5.2

### PR DESCRIPTION
**Pull request by PurvaPatidar-Tiger**
Files for Assignment 5.2 added

### CODE REVIEW

**Review by ajaykamal3 — COMMENTED** [review]
Can you attach screenshots of running this docker image and what outputs are coming after running it?

**Comment by PurvaPatidar-Tiger** [comment]
> Can you attach screenshots of running this docker image and what outputs are coming after running it?

Yes, sure I will
Screenshot (20)
.

In the Docker_container folder there is no data folder, but after running the docker file the data folder is formed.
Which has the following structure:
data
├── models
│   ├── DecisionTreeRegressor.pkl
│   ├── LinearRegression.pkl
│   └── RandomForestRegressor.pkl
├── processed
│   ├── housing_test.csv
│   └── housing_train.csv
└── raw
    └── housing.csv

**Comment by ajaykamal3** [comment]
Can you run the main.py file and show the output

**Comment by PurvaPatidar-Tiger** [comment]
> Can you run the main.py file and show the output

Sure
Screenshot (24)

**Review by ajaykamal3 — APPROVED** [review]
Approved

**Pull request merged**
